# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '15.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import sys
import re
import os

class Ui_Wind(object):
    def setupUi(self, Wind):
        Wind.setObjectName("Wind")
        Wind.setFixedSize(948, 803)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        Wind.setFont(font)
        Wind.setAcceptDrops(False)
        Wind.setStyleSheet("background-color:rgb(255, 217, 179)")
        self.listView = QtWidgets.QListView(Wind)
        self.listView.setGeometry(QtCore.QRect(-10, 80, 981, 91))
        self.listView.setStyleSheet("background-color: rgb(243, 194, 147)")
        self.listView.setObjectName("listView")
        
        self.pushButton = QtWidgets.QPushButton(Wind)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setWhatsThis("")
        self.pushButton.setAccessibleName("")
        self.pushButton.setStyleSheet("background-color:\n""")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(230, 200))
        self.pushButton.setObjectName("pushButton")
        
        self.listView_2 = QtWidgets.QListView(Wind)
        self.listView_2.setGeometry(QtCore.QRect(50, 170, 191, 811))
        self.listView_2.setStyleSheet("background-color: rgb(255, 221, 187)")
        self.listView_2.setObjectName("listView_2")
        self.pushButton_2 = QtWidgets.QPushButton(Wind)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 0, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setWhatsThis("")
        self.pushButton_2.setAccessibleName("")
        self.pushButton_2.setStyleSheet("background-color:\n""")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("мясо2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(230, 200))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(Wind)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 0, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setWhatsThis("")
        self.pushButton_3.setAccessibleName("")
        self.pushButton_3.setStyleSheet("background-color:\n""")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("xlewb.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(230, 200))
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.pushButton_4 = QtWidgets.QPushButton(Wind)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 0, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setWhatsThis("")
        self.pushButton_4.setAccessibleName("")
        self.pushButton_4.setStyleSheet("background-color:\n""")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("таврары.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(230, 200))
        self.pushButton_4.setObjectName("pushButton_4")
        
        self.listWidget = QtWidgets.QListWidget(Wind)
        self.listWidget.setGeometry(QtCore.QRect(90, 190, 321, 421))
        self.listWidget.setStyleSheet("background-color: rgb(255, 221, 179)")
        self.listWidget.setObjectName("listWidget")
        
        self.listWidget_2 = QtWidgets.QListWidget(Wind)
        self.listWidget_2.setGeometry(QtCore.QRect(590, 190, 321, 421))
        self.listWidget_2.setStyleSheet("background-color: rgb(255, 221, 179)")
        self.listWidget_2.setObjectName("listWidget_2")
        
        self.pushButton_5 = QtWidgets.QPushButton(Wind)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 330, 131, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        
        self.pushButton_6 = QtWidgets.QPushButton(Wind)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 410, 131, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        
        self.pushButton_7 = QtWidgets.QPushButton(Wind)
        self.pushButton_7.setGeometry(QtCore.QRect(680, 650, 141, 71))
        self.pushButton_7.setObjectName("pushButton_7")
        
        self.pushButton_9 = QtWidgets.QPushButton(Wind)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 650, 81, 71))
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("изображение_2021-04-24_223918-removebg-preview.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_9.setObjectName("pushButton_9")

        self.pushButton_10 = QtWidgets.QPushButton(Wind)
        self.pushButton_10.setGeometry(QtCore.QRect(890, 755, 51, 41))
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("vixid.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(25, 50))
        self.pushButton_10.setObjectName("pushButton_10")

        self.tableWidget = QtWidgets.QTableView(Wind)
        self.tableWidget.setGeometry(QtCore.QRect(100, 200, 301, 401))
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget1 = QtWidgets.QTableView(Wind)
        self.tableWidget1.setGeometry(QtCore.QRect(600, 200, 301, 401))
        self.tableWidget1.setObjectName("tableWidget1")

        self.retranslateUi(Wind)
        QtCore.QMetaObject.connectSlotsByName(Wind)

    def retranslateUi(self, Wind):
        _translate = QtCore.QCoreApplication.translate
        Wind.setWindowTitle(_translate("Wind", "Пампейка"))
        self.pushButton_5.setText(_translate("Wind", "Взять"))
        self.pushButton_6.setText(_translate("Wind", "Выгрузить"))
        self.pushButton_7.setText(_translate("Wind", "Купить"))

    def show_window_2(self):  # открытие 2  окна 
        self.w2 = Window2()
        self.w2.show()
        
class MainWindow(QtWidgets.QMainWindow, Ui_Wind):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget1.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        self.pushButton.clicked.connect(self.milk)
        self.pushButton_2.clicked.connect(self.mco)
        self.pushButton_3.clicked.connect(self.xlebw)
        self.pushButton_4.clicked.connect(self.hometov)
        self.pushButton_5.clicked.connect(self.add_row)
        self.pushButton_6.clicked.connect(self.on_del_record)
        self.pushButton.clicked.connect(self.pokypki)
        self.pushButton_2.clicked.connect(self.pokypki)
        self.pushButton_3.clicked.connect(self.pokypki)
        self.pushButton_4.clicked.connect(self.pokypki)
        self.pushButton_9.clicked.connect(self.play)
        self.pushButton_7.clicked.connect(self.show_window_2)
        self.pushButton_10.clicked.connect(sys.exit)
        
        db = QSqlDatabase.addDatabase('QSQLITE')
        db.setDatabaseName('Продукты.db')
        db.open()
        self.pw()
        
    def milk(self, Ui_Wind):
        self.model = QSqlTableModel(self)
        self.model.setTable("Молочная_продукция")
        self.model.setHeaderData(0, Qt.Horizontal, "Название")
        self.model.setHeaderData(2, Qt.Horizontal, "Цена")
        sql = "SELECT * FROM"
        self.model.select()
        sql = "SELECT Наименование FROM Молочная_продукция limit %d" % (0)
        self.tableWidget.setModel(self.model)

    def mco(self, Ui_Wind):
        self.model = QSqlTableModel(self)
        self.model.setTable("Мясная_продукция")
        self.model.setHeaderData(0, Qt.Horizontal, "Название")
        self.model.setHeaderData(2, Qt.Horizontal, "Цена")
        sql = "SELECT * FROM"
        self.model.select()
        sql = "SELECT Наименование FROM Мясная_продукция limit %d" % (0)
        self.tableWidget.setModel(self.model)

    def xlebw(self, Ui_Wind):
        self.model = QSqlTableModel(self)
        self.model.setTable("Хлебобулочные_Изделия")
        self.model.setHeaderData(0, Qt.Horizontal, "Название")
        self.model.setHeaderData(2, Qt.Horizontal, "Цена")
        sql = "SELECT * FROM"
        self.model.select()
        sql = "SELECT Наименование FROM Хлебобулочные_Изделия limit %d" % (0)
        self.tableWidget.setModel(self.model)

    def hometov(self, Ui_Wind):
        self.model = QSqlTableModel(self)
        self.model.setTable("Товары_Для_Дома")
        self.model.setHeaderData(0, Qt.Horizontal, "Название")
        self.model.setHeaderData(2, Qt.Horizontal, "Цена")
        sql = "SELECT * FROM"
        self.model.select()
        sql = "SELECT Наименование FROM Товары_Для_Дома limit %d" % (0)
        self.tableWidget.setModel(self.model)

    def pokypki(self, Ui_Wind):
        self.model_purchases = QSqlTableModel(self)
        self.model_purchases.setTable("Покупки")                # Покупки
        self.model_purchases.select()
        self.tableWidget1.setModel(self.model_purchases)

    def add_row(self, Ui_Wind):
        row = self.tableWidget.currentIndex().row()
        if row == -1:
            msg = QMessageBox.information(self, 'Внимание', 'Выберите продукт для покупки.')
            return
        name = self.model.record(row).value(0)
        opisanie = self.model.record(row).value(1)
        price = self.model.record(row).value(2)
        
        r = self.model_purchases.record()
        r.setValue("Наименование", name)
        r.setValue("Описание", opisanie)
        r.setValue("Цена", price)        
        self.model_purchases.insertRecord(-1, r)
        self.model_purchases.select()   

    sys.excepthook = add_row

    def on_del_record(self, Ui_Wind):
        row = self.tableWidget1.currentIndex().row()
        if row == -1:
            msg = QMessageBox.information(self, 'Внимание', 'Выберите продукт для выгрузки.')
            return

        self.model_purchases.removeRow(self.tableWidget1.currentIndex().row())
        self.model_purchases.select()

        self.model.select()
        
    def pw(self):
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget1.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

    def play(self):
        os.system("Mark1.mp4")
        
class Window2(QtWidgets.QMainWindow, Ui_Wind):
    def __init__(self):
        super(Window2, self).__init__()
        self.initt()
        self.pokypki1()
        db1 = QSqlDatabase.addDatabase('QSQLITE')
        db1.setDatabaseName('Продукты.db')
        db1.open()
        
    def initt(self):
        cur.execute("SELECT SUM(count) FROM users")
        result = a.fetchone()[0]
        l1 = QLabel(self)
        l2 = QLabel(self)
        l3 = QLabel(self)
        l1.setText("""*****************************************************
    ООО "Пампейка" 545, Место сбыта товара находится по адресу
    г.Екатеринбург, ул. Вильгельм де Геннина          
         Платёж совершён: онлайн                   
         Копия: 1                           
         Чек:00001                           
        ****************************************************  
        Терминал: 235645545 Мерчант:1910000001           
        Карта(E)
        Уважаемые покупатели! При наличии претензий,  
        просим вас направлять письменое обращение на почту  
               Super_Puper545@mail.ru 
         ****************************************************                            """)
        l1.setAlignment(Qt.AlignCenter)
        l1.setOpenExternalLinks(True)
        l1.setTextInteractionFlags(Qt.TextSelectableByMouse)
        l2.setAlignment(Qt.AlignCenter)
        l2.setToolTip('Pampeika')
        l2.setPixmap(QPixmap("qrrr.png"))
        l3.setAlignment(Qt.AlignCenter)
        l3.setOpenExternalLinks(True)
        l3.setTextInteractionFlags(Qt.TextSelectableByMouse)
        l3.setText("Итого: ", result)
        vbox = QVBoxLayout()
        vbox.addWidget(l1)
        vbox.addWidget(l2)
        vbox.addWidget(l3)
        vbox.addStretch()
        self.setGeometry(500,150,500,800)
        self.setLayout(vbox)
        l1.resize(500,270)
        l2.resize(240,600)
        l3.resize(550,1500)
        self.setWindowTitle('Чек')
        self.listView1 = QtWidgets.QListView(self)
        self.listView1.setGeometry(QtCore.QRect(70, 350, 351, 371))
        self.listView1.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.listView1.setObjectName("listView1")
        
    def pokypki1(self):
        self.model_purchases = QSqlTableModel(self)
        self.model_purchases.setTable("Покупки")                # Покупки
        self.model_purchases.select()
        self.listView1.setModel(self.model_purchases)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())
