bicycles = ['trek','cannondale','redline','specialized']
print(bicycles[0].title())
print(bicycles[-1].upper())
message = f'My first bicycle was {bicycles[0].upper()}. And you?'
print("______________________")
names = ['Jopa','Gawno','Piska','Mo4a']
print(names[0])
print(names[-1].title())
print(names[-2].upper())
print(names[1].lower())
print(f'My best friend {names[-1].title()}!')
print("______________________")
motocycles = ['honda','yamaha','suzuki']
print(motocycles)
'''motocycles[0] = 'ducati'
print(motocycles)
motocycles.append('ducati')
motocycles.insert(0, 'Gownina')
print(motocycles)
del motocycles[1]
print(motocycles)
last_owned = motocycles.pop()
print(f'The last motocycle I owned was a {last_owned.title()}.')
popped_motocycles = motocycles.pop()
print(popped_motocycles)'''
first_owned = motocycles.pop(0)
print(f'The first motocycles I owned was a {first_owned.title()}.')
print(motocycles)
too_expensive = 'yamaha'
motocycles.remove(too_expensive)
print(motocycles)
print(f'\nA {too_expensive.title()} is too expensive for me.')
print("______________________")
invitations = ['Patrick', 'Blanka','Syama','Bagira','Snezhok','Alabay']
print(invitations)
print(f'Hello my pets, i love you, and i invite you {invitations[0].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[1].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[2].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[3].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[4].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[5].title()}!')
print("Alabay: sorry i can't do it")
he_cant = invitations.pop(5)
print(f'So sorry {he_cant}, we will wait for the next time.')
new_invite = invitations.insert(5, 'Baladay')
print(invitations)
print(f'Hello my pets, i love you, and i invite you {invitations[0].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[1].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[2].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[3].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[4].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[5].title()}!')
print("Hohoho! My table has increased!")
invitations.insert(0, 'Nobody')
invitations.insert(-1, 'Body')
invitations.insert(4, 'Bydo')
print(invitations)
print(f'Hello my pets, i love you, and i invite you {invitations[0].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[1].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[2].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[3].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[4].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[5].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[6].title()}!')
print(f'Hello my pets, i love you, and i invite you {invitations[7].title()}!')
print("Oh no! A tabel! His brooken!")
print(invitations)
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(f'So sorry {invitations.pop()}, we will wait for the next time.')
print(invitations)
print(f'Lesgo party time {invitations[0]}!')
print(f'Lesgo party time {invitations[1]}!')
print(len(invitations))
del invitations[-1]
del invitations[0]
print(invitations)
print("______________________")
cars = ['bmw','audi','toyota','subaru']
#cars.sort(reverse=True)
print('Here is the original list:')
print(cars)
print('\nHere is the sorted list:')
print(sorted(cars))
print('\nHere is the original list.. again:')
print(cars)
cars.reverse()
print(cars)
countries = ['Poland','Finland','Australia','Baku','Brazilia']
print(countries)
print(sorted(countries))
print(sorted(countries, reverse=True))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)