# Generated by Django 4.1.7 on 2023-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrology',
            old_name='created_ad',
            new_name='data_Power',
        ),
        migrations.RenameField(
            model_name='metrology',
            old_name='content',
            new_name='name_SI',
        ),
        migrations.RenameField(
            model_name='metrology',
            old_name='title',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='metrology',
            name='is_published',
        ),
        migrations.AddField(
            model_name='metrology',
            name='registration_number',
            field=models.TextField(blank=True),
        ),
    ]
