# Generated by Django 4.1.7 on 2023-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0002_rename_created_ad_metrology_data_power_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrology',
            options={'ordering': ['-data_Power'], 'verbose_name': 'Стандарт', 'verbose_name_plural': 'Стандарты'},
        ),
        migrations.AlterField(
            model_name='metrology',
            name='data_Power',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='metrology',
            name='name_SI',
            field=models.TextField(verbose_name='Наименование типа СИ'),
        ),
        migrations.AlterField(
            model_name='metrology',
            name='organisation',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='metrology',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='metrology',
            name='registration_number',
            field=models.TextField(blank=True, verbose_name='Регистрационный номер'),
        ),
    ]
