# Generated by Django 4.1.7 on 2023-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0003_alter_metrology_options_alter_metrology_data_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=150, verbose_name='Наименование предложения')),
                ('name_SI', models.TextField(verbose_name='Наименование типа СИ')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Предложения',
                'verbose_name_plural': 'Предложения',
                'ordering': ['organisation'],
            },
        ),
    ]
